// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var trackEvent, trackOutboundLink;
    trackEvent = function(str) {
      return ga("send", "event", "button", "click", str, 1);
    };
    trackOutboundLink = function(url) {
      return ga("send", "event", "outbound", "click", url, {
        hitCallback: function() {
          return document.location = url;
        }
      });
    };
    $(".flags").on("click", "li", function(event) {
      return trackEvent("Demo: Panel item");
    });
    $(".dom-tree").on("click", ".tooltip", function(event) {
      return trackEvent("Demo: tooltip " + event.target.textContent.toLowerCase());
    });
    return $('.marketing-info').on("click", "a", function(event) {
      if (event.target.id === "install-button") {
        trackEvent("Marketing: Inline Install");
      } else {
        trackOutboundLink(event.target.href);
      }
      return false;
    });
  });

}).call(this);
